name: validate-release-pr

on:
  pull_request_target:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  build:
    if: startsWith(github.head_ref, 'release-please--')
    uses: ./.github/workflows/build.yml
